apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: web-service
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: docker.io/ciaa/web:v0.2.0
          resources:
            limits:
              memory: "1000Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Pod
metadata:
  name: caller-pod
  namespace: default
spec:
  containers:
  - name: caller
    image: docker.io/ciaa/caller:v0.2.0