apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: docker.io/ciaa/web:v0.5.0
          resources:
            limits:
              memory: "2000Mi"
              cpu: "2000m"
          env:
          - name: AWS_DEFAULT_REGION
            value: "${AWS_DEFAULT_REGION}"
          - name: AWS_ACCESS_KEY_ID
            value: "${AWS_ACCESS_KEY_ID}"
          - name: AWS_SECRET_ACCESS_KEY
            value: "${AWS_SECRET_ACCESS_KEY}"
          - name: S3_ENDPOINT_URL
            value: "${S3_ENDPOINT_URL}"
          - name: S3_BUCKET
            value: "${S3_BUCKET}"
          ports:
            - containerPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caller-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: caller-app
  template:
    metadata:
      labels:
        app: caller-app
    spec:
      containers:
        - name: caller-app
          image: docker.io/ciaa/caller:v0.5.0
          resources:
            limits:
              memory: "1000Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: default
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: caller-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: caller-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000